export { store } from './store';
export { default as rootReducer } from './reducers';
export { default as rootSaga } from './sagas';

// Re-export all actions
export {
  loginRequest,
  loginSuccess,
  loginFailure,
  registerRequest,
  registerSuccess,
  registerFailure,
  forgotPasswordRequest,
  forgotPasswordSuccess,
  forgotPasswordFailure,
  logout,
  clearAuthError,
  setAuthLoading,
} from './slices/authSlice';

export {
  fetchAppointmentsRequest,
  fetchAppointmentsSuccess,
  fetchAppointmentsFailure,
  bookAppointmentRequest,
  bookAppointmentSuccess,
  bookAppointmentFailure,
  cancelAppointmentRequest,
  cancelAppointmentSuccess,
  cancelAppointmentFailure,
  rescheduleAppointmentRequest,
  rescheduleAppointmentSuccess,
  rescheduleAppointmentFailure,
  checkInRequest,
  checkInSuccess,
  checkInFailure,
  generatePrescriptionRequest,
  generatePrescriptionSuccess,
  generatePrescriptionFailure,
  processPaymentRequest,
  processPaymentSuccess,
  processPaymentFailure,
  clearBookingError,
  setBookingLoading,
  resetBooking,
} from './slices/bookingSlice';

// Re-export all selectors
export {
  selectAuthState,
  selectUser,
  selectIsAuthenticated,
  selectAuthLoading,
  selectAuthError,
  selectForgotPasswordMessage,
  selectUserName,
  selectUserEmail,
  selectUserRole,
  selectBookingState,
  selectAppointments,
  selectBookingLoading,
  selectBookingError,
  selectCheckIns,
  selectPrescriptions,
  selectInvoices,
  selectTodaysAppointments,
  selectUpcomingAppointments,
  selectCancelledAppointments,
  selectOnlineConsultations,
  selectConfirmedAppointments,
  selectPendingAppointments,
  selectTotalAppointments,
  selectUniquePatients,
  selectAppointmentById,
  selectAppointmentsByDoctor,
  selectAppointmentsByDate,
} from './selectors';
